[project]
name = "neostore"
version = "0.1.0"
description = "A tech store management system's backend service app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.11",
]
